feat: add hero section
dscnitrourkela/project-huckleberry pull request #35
Opened 2023-09-03 20:01 UTC by Shurtu-gal

### Your checklist for this pull request

🚨Please review the [guidelines for contributing](https://github.com/dscnitrourkela/project-huckleberry/blob/main/CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [x] Make sure you are making a pull request against the **default branch** (left side). Also you should start _your branch_ off _default branch_.
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.
- [x] I have added necessary documentation (if appropriate)

### Linked Issues

Fixes

### Description

Please describe your pull request.

❤️Thank you!

### Post merge checklist

- [x] Follow steps from the [guidelines for contributing](https://github.com/dscnitrourkela/project-huckleberry/blob/main/CONTRIBUTING.md) to this repository.

2023-09-05 15:20 UTC, Lucif3r-in commented
![image](https://github.com/dscnitrourkela/project-huckleberry/assets/85403534/bb09d1ec-1a65-49ba-b0bd-0853cf078ed8)
The `Web Dev` and `App Dev` texts should be in column as they are touching the circle borders.  Also keep the gap between the animation and navbar(refer image).

2023-09-05 15:25 UTC, Lucif3r-in commented
The animation is starting from a point in extreme left of the container. If possible start from the center of pentagon or from their respective corners.

2023-09-05 17:01 UTC, Lucif3r-in requested changes

2023-09-27 10:38 UTC, Shurtu-gal commented on src/components/atoms/Hero/AnimatedDomain/styles.jsx
> +	}
Not currently

2023-09-27 10:43 UTC, merged